project:
  type: website

website:
  title: "Andrew Nguyen"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: dashboard.qmd
        text: Dashboard
      - href: presentation.qmd
        text: Presentation
    right:
      - icon: github
        href: https://github.com
embed-resources: True
format:
  html:
    theme: cosmo
    css: styles.css

